/** Dictionary fallback for European buyer languages, keyed by the English text. */
type D = Record<string, string>;

const it: D = {
  "About the group": "Il gruppo", "All rights reserved.": "Tutti i diritti riservati.", "Contact us for export": "Contattaci per l'export", "Cultivating quality,": "Coltiviamo qualità,", "exporting ": "esportiamo ", "excellence.": "eccellenza.", "Developed by": "Sviluppato da", "Export portfolio": "Portafoglio export", "Export routes": "Rotte di esportazione", "Fresh, frozen & processed": "Fresco, surgelato e trasformato", "From the farm to the world": "Dal campo al mondo", "Global reach": "Presenza globale", "Our certificates": "Le nostre certificazioni", "Our partners": "I nostri partner", "Our products": "I nostri prodotti", "Product gallery": "Galleria prodotti", "Quality journey": "Il percorso qualità", "Quality & compliance": "Qualità e conformità", "We deliver to the strongest markets": "Serviamo i mercati più esigenti", "Where we export": "Dove esportiamo", "Markets we serve": "Mercati serviti", "Who we deal with": "Con chi lavoriamo", "Let's grow together": "Cresciamo insieme", "Logistics": "Logistica", "Infrastructure": "Infrastrutture", "Packing & shipping details": "Imballaggio e spedizione", "Message sent — our export team will reply soon.": "Messaggio inviato — il team export risponderà a breve.", "Fresh Produce": "Prodotti freschi", "IQF Frozen": "Surgelati IQF", "Processed": "Trasformati", "Fresh grapes": "Uva fresca", "Fresh vegetables": "Verdure fresche", "Frozen IQF produce": "Prodotti surgelati IQF", "Fresh Grapes": "Uva fresca", "Fresh Artichokes": "Carciofi freschi", "Fresh Strawberries": "Fragole fresche", "IQF Green Peas": "Piselli IQF", "IQF Broccoli": "Broccoli IQF", "IQF Carrots": "Carote IQF", "IQF Okra": "Okra IQF", "Watermelon": "Anguria", "Green Beans": "Fagiolini", "Cauliflower": "Cavolfiore", "Spring Onions": "Cipollotti", "Coloured Peppers": "Peperoni colorati", "Years of experience": "Anni di esperienza", "Countries": "Paesi",
};
const fr: D = {
  "About the group": "Le groupe", "All rights reserved.": "Tous droits réservés.", "Contact us for export": "Contactez-nous pour l'export", "Cultivating quality,": "Cultiver la qualité,", "exporting ": "exporter ", "excellence.": "l'excellence.", "Developed by": "Développé par", "Export portfolio": "Portefeuille export", "Export routes": "Routes d'export", "Fresh, frozen & processed": "Frais, surgelé et transformé", "From the farm to the world": "De la ferme au monde", "Global reach": "Présence mondiale", "Our certificates": "Nos certificats", "Our partners": "Nos partenaires", "Our products": "Nos produits", "Product gallery": "Galerie produits", "Quality journey": "Parcours qualité", "Quality & compliance": "Qualité et conformité", "We deliver to the strongest markets": "Nous livrons les marchés les plus exigeants", "Where we export": "Où nous exportons", "Markets we serve": "Nos marchés", "Who we deal with": "Nos clients", "Let's grow together": "Grandissons ensemble", "Logistics": "Logistique", "Infrastructure": "Infrastructures", "Packing & shipping details": "Emballage et expédition", "Message sent — our export team will reply soon.": "Message envoyé — notre équipe export vous répondra bientôt.", "Fresh Produce": "Produits frais", "IQF Frozen": "Surgelés IQF", "Processed": "Transformés", "Fresh grapes": "Raisins frais", "Fresh vegetables": "Légumes frais", "Frozen IQF produce": "Produits surgelés IQF", "Fresh Grapes": "Raisins frais", "Fresh Artichokes": "Artichauts frais", "Fresh Strawberries": "Fraises fraîches", "IQF Green Peas": "Petits pois IQF", "IQF Broccoli": "Brocoli IQF", "IQF Carrots": "Carottes IQF", "IQF Okra": "Gombo IQF", "Watermelon": "Pastèque", "Green Beans": "Haricots verts", "Cauliflower": "Chou-fleur", "Spring Onions": "Oignons verts", "Coloured Peppers": "Poivrons colorés", "Years of experience": "Années d'expérience", "Countries": "Pays",
};
const de: D = {
  "About the group": "Die Gruppe", "All rights reserved.": "Alle Rechte vorbehalten.", "Contact us for export": "Export-Anfrage", "Cultivating quality,": "Wir kultivieren Qualität,", "exporting ": "und exportieren ", "excellence.": "Exzellenz.", "Developed by": "Entwickelt von", "Export portfolio": "Exportportfolio", "Export routes": "Exportrouten", "Fresh, frozen & processed": "Frisch, tiefgekühlt & verarbeitet", "From the farm to the world": "Vom Feld in die Welt", "Global reach": "Weltweite Präsenz", "Our certificates": "Unsere Zertifikate", "Our partners": "Unsere Partner", "Our products": "Unsere Produkte", "Product gallery": "Produktgalerie", "Quality journey": "Qualitätsweg", "Quality & compliance": "Qualität & Compliance", "We deliver to the strongest markets": "Wir beliefern die anspruchsvollsten Märkte", "Where we export": "Wohin wir exportieren", "Markets we serve": "Unsere Märkte", "Who we deal with": "Unsere Kunden", "Let's grow together": "Gemeinsam wachsen", "Logistics": "Logistik", "Infrastructure": "Infrastruktur", "Packing & shipping details": "Verpackung & Versand", "Message sent — our export team will reply soon.": "Nachricht gesendet — unser Export-Team meldet sich bald.", "Fresh Produce": "Frischware", "IQF Frozen": "IQF-Tiefkühlware", "Processed": "Verarbeitet", "Fresh grapes": "Frische Trauben", "Fresh vegetables": "Frisches Gemüse", "Frozen IQF produce": "IQF-Tiefkühlprodukte", "Fresh Grapes": "Frische Tafeltrauben", "Fresh Artichokes": "Frische Artischocken", "Fresh Strawberries": "Frische Erdbeeren", "IQF Green Peas": "IQF-Erbsen", "IQF Broccoli": "IQF-Brokkoli", "IQF Carrots": "IQF-Karotten", "IQF Okra": "IQF-Okra", "Watermelon": "Wassermelone", "Green Beans": "Grüne Bohnen", "Cauliflower": "Blumenkohl", "Spring Onions": "Frühlingszwiebeln", "Coloured Peppers": "Bunte Paprika", "Years of experience": "Jahre Erfahrung", "Countries": "Länder",
};

export const phrases: Partial<Record<string, D>> = { it, fr, de };
